#!/usr/bin/env node
/**
 * Standalone BullMQ Dashboard
 *
 * Run with: npx tsx scripts/bullmq-dashboard.ts
 * Or after build: node dist/scripts/bullmq-dashboard.js
 *
 * Provides a web UI to monitor BullMQ queues with authentication.
 */

import express from "express";
import crypto from "crypto";
import fs from "fs";
import os from "os";
import path from "path";

// Load environment variables from .env file
try {
  const { config } = await import("dotenv");
  config();
} catch {
}

// Check for optional dependencies before importing
let createBullBoard: typeof import("@bull-board/api").createBullBoard;
let BullMQAdapter: typeof import("@bull-board/api/bullMQAdapter").BullMQAdapter;
let ExpressAdapter: typeof import("@bull-board/express").ExpressAdapter;
let Queue: typeof import("bullmq").Queue;

const missingDeps: string[] = [];

try {
  const bullBoardApi = await import("@bull-board/api");
  createBullBoard = bullBoardApi.createBullBoard;
} catch {
  missingDeps.push("@bull-board/api");
}

try {
  const bullMQAdapter = await import("@bull-board/api/bullMQAdapter");
  BullMQAdapter = bullMQAdapter.BullMQAdapter;
} catch {
  missingDeps.push("@bull-board/api/bullMQAdapter");
}

try {
  const expressAdapter = await import("@bull-board/express");
  ExpressAdapter = expressAdapter.ExpressAdapter;
} catch {
  missingDeps.push("@bull-board/express");
}

try {
  const bullmq = await import("bullmq");
  Queue = bullmq.Queue;
} catch {
  missingDeps.push("bullmq");
}

if (missingDeps.length > 0) {
  console.error("Error: Missing optional dependencies required for BullMQ Dashboard:");
  console.error(`  ${missingDeps.join(", ")}`);
  console.error("\nInstall them with:");
  console.error(`  pnpm add ${missingDeps.join(" ")}`);
  console.error("\nOr for development:");
  console.error(`  pnpm add -D ${missingDeps.join(" ")}`);
  process.exit(1);
}

const PORT = process.env.BULLMQ_DASHBOARD_PORT || "3000";
const REDIS_URL = process.env.REDIS_URL || "redis://localhost:6379";

// Track if password was auto-generated
let isAutoGeneratedPassword = false;

// Authentication configuration
const AUTH_ENABLED = process.env.BULLMQ_DASHBOARD_AUTH_ENABLED !== "false";
const USERNAME = process.env.BULLMQ_DASHBOARD_USERNAME || "admin";
const PASSWORD =
  process.env.BULLMQ_DASHBOARD_PASSWORD?.toString() || (isAutoGeneratedPassword = true, generateAndStorePassword());

/**
 * Generate a secure random password and store it in a temp file.
 * This ensures the dashboard is not exposed with a default weak password,
 * but the user can retrieve it when needed.
 */
function generateAndStorePassword(): string {
  const password = crypto.randomBytes(32).toString("hex");
  const tempFile = path.join(os.tmpdir(), `bullmq-dashboard-${process.pid}.txt`);
  fs.writeFileSync(tempFile, password, { mode: 0o600 }); // Read-only by owner
  console.log(`\n Auto-generated password stored in: ${tempFile}`);
  console.log(`   Run this to view: cat ${tempFile}`);
  return password;
}


/**
 * Basic authentication middleware.
 * Protects the dashboard from unauthorized access.
 */
function authMiddleware(
  req: express.Request,
  res: express.Response,
  next: express.NextFunction,
): void {
  if (!AUTH_ENABLED) {
    next();
    return;
  }

  const authHeader = req.headers.authorization;

  if (!authHeader || !authHeader.startsWith("Basic ")) {
    res.setHeader("WWW-Authenticate", 'Basic realm="BullMQ Dashboard"');
    res.status(401).send("Authentication required");
    return;
  }

  const credentials = Buffer.from(authHeader.slice(6), "base64").toString(
    "utf-8",
  );
  const [user, pass] = credentials.split(":");

  // Use timing-safe comparison to prevent timing attacks
  // Compare SHA-256 hashes since timingSafeEqual requires equal-length buffers
  const userMatch = crypto.timingSafeEqual(
    crypto.createHash("sha256").update(user || "").digest(),
    crypto.createHash("sha256").update(USERNAME).digest(),
  );
  const passMatch = crypto.timingSafeEqual(
    crypto.createHash("sha256").update(pass || "").digest(),
    crypto.createHash("sha256").update(PASSWORD).digest(),
  );

  if (!userMatch || !passMatch) {
    res.setHeader("WWW-Authenticate", 'Basic realm="BullMQ Dashboard"');
    res.status(401).send("Invalid credentials");
    return;
  }

  next();
}

async function main() {
  const app = express();

  // Security: Disable x-powered-by header
  app.disable("x-powered-by");

  // Health check endpoint (no auth required)
  app.get("/health", (_req, res) => {
    res.json({ status: "ok", timestamp: new Date().toISOString() });
  });

  const serverAdapter = new ExpressAdapter();

  // Connect to the neurolink-scheduler queue
  const queue = new Queue("neurolink-scheduler", {
    connection: { url: REDIS_URL },
  });

  createBullBoard({
    queues: [new BullMQAdapter(queue)],
    serverAdapter,
    options: {
      uiConfig: {
        boardTitle: "NeuroLink Task Scheduler Dashboard",
      },
    },
  });

  serverAdapter.setBasePath("/");

  // Apply authentication middleware to the dashboard routes
  app.use("/", authMiddleware, serverAdapter.getRouter());

  app.listen(Number(PORT), "127.0.0.1", () => {
    console.log(`BullMQ Dashboard running at http://localhost:${PORT}`);
    console.log(`Monitoring queue: neurolink-scheduler`);
    console.log(`Redis: ${REDIS_URL.replace(/:\/\/[^:]+:/, "://***:***@")}`);

    if (AUTH_ENABLED) {
      console.log(`\n⚠️  Authentication enabled`);
      console.log(`   Username: ${USERNAME}`);
      console.log(
        `   Password: ${process.env.BULLMQ_DASHBOARD_PASSWORD ? "[from env]" : "[auto-generated, see below]"}`,
      );
      if (isAutoGeneratedPassword) {
        const tempFile = `/tmp/bullmq-dashboard-${process.pid}.txt`;
        console.log(`\n   Generated Password: stored in ${tempFile}`);
        console.log(`   View with: cat ${tempFile}`);
      } else {
        console.log(`\n   Password: [from env]`);
      }
    } else {
      console.log(`\n⚠️  Authentication is DISABLED`);
      console.log(`   Set BULLMQ_DASHBOARD_AUTH_ENABLED=true to enable auth`);
    }
  });
}

main().catch((err) => {
  console.error("Failed to start dashboard:", err);
  process.exit(1);
});
