/**
 * Server Generator - Creates Hono-based HTTP server
 *
 * Generates:
 * - Main server entry (index.mjs)
 * - API router with all routes
 * - OpenAPI documentation
 * - Playground UI (optional)
 *
 * @packageDocumentation
 * @module @juspay/neurolink/deployer
 * @category Deployment
 */

import fs from "node:fs";
import path from "node:path";
import { logger } from "../../utils/logger.js";
import type {
  ServerConfig,
  BuildOutput,
  OutputFile,
  DiscoveredEntries,
  DiscoveredTool,
} from "../types.js";

/**
 * Generated server result
 */
export type GeneratedServer = {
  /** Server code content */
  code: string;

  /** Router code content */
  router: string;

  /** OpenAPI spec (if enabled) */
  openApiSpec?: string;

  /** Playground HTML (if enabled) */
  playgroundHtml?: string;
};

/**
 * Server Generator - Creates complete HTTP server for deployment
 *
 * @example
 * ```typescript
 * const generator = new ServerGenerator({
 *   port: 8080,
 *   openapi: true,
 *   playground: true
 * });
 * const server = await generator.generate(outputDir);
 *
 * console.log('Server code generated');
 * ```
 */
export class ServerGenerator {
  private config: ServerConfig;

  constructor(config: ServerConfig = {}) {
    this.config = config;
  }

  /**
   * Generate complete server
   */
  async generate(
    outputDir: string,
    tools?: DiscoveredTool[]
  ): Promise<GeneratedServer> {
    // Generate server code
    const serverCode = this.generateServerCode();

    // Write server entry
    const serverPath = path.join(outputDir, "index.mjs");
    fs.writeFileSync(serverPath, serverCode);

    // Generate router
    const routerCode = this.generateRouterCode(tools);
    const routerPath = path.join(outputDir, "router.mjs");
    fs.writeFileSync(routerPath, routerCode);

    const result: GeneratedServer = {
      code: serverCode,
      router: routerCode,
    };

    // Generate OpenAPI spec if enabled
    if (this.config.openapi) {
      result.openApiSpec = this.generateOpenApiSpec();
      const specPath = path.join(outputDir, "openapi.json");
      fs.writeFileSync(specPath, result.openApiSpec);
    }

    // Generate playground if enabled
    if (this.config.playground) {
      result.playgroundHtml = this.generatePlayground();
      const playgroundDir = path.join(outputDir, "public");
      fs.mkdirSync(playgroundDir, { recursive: true });
      const playgroundPath = path.join(playgroundDir, "playground.html");
      fs.writeFileSync(playgroundPath, result.playgroundHtml);
    }

    logger.info("Server generated", {
      serverPath,
      routerPath,
      hasOpenApi: !!result.openApiSpec,
      hasPlayground: !!result.playgroundHtml,
    });

    return result;
  }

  /**
   * Get generated file list
   */
  getGeneratedFiles(result: GeneratedServer): OutputFile[] {
    const files: OutputFile[] = [
      {
        path: "index.mjs",
        size: Buffer.byteLength(result.code),
        type: "js",
      },
      {
        path: "router.mjs",
        size: Buffer.byteLength(result.router),
        type: "js",
      },
    ];

    if (result.openApiSpec) {
      files.push({
        path: "openapi.json",
        size: Buffer.byteLength(result.openApiSpec),
        type: "json",
      });
    }

    if (result.playgroundHtml) {
      files.push({
        path: "public/playground.html",
        size: Buffer.byteLength(result.playgroundHtml),
        type: "html",
      });
    }

    return files;
  }

  /**
   * Generate main server code
   */
  private generateServerCode(): string {
    const port = this.config.port || 8080;
    const basePath = this.config.basePath || "/api";
    const cors = this.config.cors !== false;

    return `// NeuroLink HTTP Server
// Auto-generated by NeuroLink Deployment System

import { Hono } from "hono";
import { cors } from "hono/cors";
import { logger as honoLogger } from "hono/logger";
import { prettyJSON } from "hono/pretty-json";
import { serve } from "@hono/node-server";
import { router } from "./router.mjs";

// Create Hono app
export const app = new Hono();

// Global middleware
app.use("*", honoLogger());
app.use("*", prettyJSON());
${cors ? 'app.use("*", cors());' : ""}

// Health check
app.get("/health", (c) => c.json({
  status: "ok",
  timestamp: Date.now(),
  version: process.env.npm_package_version || "1.0.0",
}));

// Mount API router
app.route("${basePath}", router);

${
  this.config.openapi
    ? `
// OpenAPI spec
app.get("/openapi.json", async (c) => {
  try {
    const fs = await import("node:fs");
    const path = await import("node:path");
    const specPath = path.join(import.meta.dirname || process.cwd(), "openapi.json");
    const spec = JSON.parse(fs.readFileSync(specPath, "utf-8"));
    return c.json(spec);
  } catch (error) {
    return c.json({ error: "OpenAPI spec not found" }, 404);
  }
});
`
    : ""
}

${
  this.config.playground
    ? `
// Playground UI
app.get("/playground", async (c) => {
  try {
    const fs = await import("node:fs");
    const path = await import("node:path");
    const htmlPath = path.join(import.meta.dirname || process.cwd(), "public", "playground.html");
    const html = fs.readFileSync(htmlPath, "utf-8");
    return c.html(html);
  } catch (error) {
    return c.html("<h1>Playground not available</h1>", 500);
  }
});
`
    : ""
}

// 404 handler
app.notFound((c) => {
  return c.json({
    error: "Not Found",
    path: c.req.path,
    method: c.req.method,
  }, 404);
});

// Error handler
app.onError((err, c) => {
  console.error("Server error:", err);
  return c.json({
    error: err.message,
    stack: process.env.NODE_ENV === "development" ? err.stack : undefined,
  }, 500);
});

// Start server (only when running directly)
const isMainModule = import.meta.url === \`file://\${process.argv[1]}\`;
if (isMainModule) {
  const serverPort = parseInt(process.env.PORT || "${port}", 10);

  console.log(\`
============================================
        NeuroLink Server Started
============================================
  URL:        http://localhost:\${serverPort}
  API:        http://localhost:\${serverPort}${basePath}
${this.config.openapi ? `  OpenAPI:    http://localhost:\${serverPort}/openapi.json` : ""}
${this.config.playground ? `  Playground: http://localhost:\${serverPort}/playground` : ""}
============================================
  \`);

  serve({
    fetch: app.fetch,
    port: serverPort,
  });
}

export default app;
`;
  }

  /**
   * Generate router code
   */
  private generateRouterCode(tools?: DiscoveredTool[]): string {
    return `// NeuroLink API Router
// Auto-generated by NeuroLink Deployment System

import { Hono } from "hono";
import { stream } from "hono/streaming";
import { NeuroLink } from "@juspay/neurolink";

// Initialize NeuroLink
const neurolink = new NeuroLink();

// Create router
export const router = new Hono();

// POST /generate - Generate text
router.post("/generate", async (c) => {
  try {
    const body = await c.req.json();

    const result = await neurolink.generate({
      prompt: body.prompt,
      model: body.model,
      provider: body.provider,
      temperature: body.temperature,
      maxTokens: body.maxTokens,
      system: body.system,
    });

    return c.json({
      content: result.content,
      provider: result.provider,
      model: result.model,
      usage: result.analytics?.usage,
    });
  } catch (error) {
    return c.json({
      error: error.message,
    }, 500);
  }
});

// POST /stream - Stream text generation
router.post("/stream", async (c) => {
  const body = await c.req.json();

  return stream(c, async (streamWriter) => {
    try {
      const result = await neurolink.stream({
        prompt: body.prompt,
        model: body.model,
        provider: body.provider,
        temperature: body.temperature,
        maxTokens: body.maxTokens,
        system: body.system,
      });

      for await (const chunk of result.stream) {
        await streamWriter.write(chunk);
      }
    } catch (error) {
      await streamWriter.write(\`Error: \${error.message}\`);
    }
  });
});

// GET /tools - List available tools
router.get("/tools", async (c) => {
  const tools = neurolink.getAvailableTools();
  return c.json({ tools });
});

// POST /tools/:toolName - Execute a tool
router.post("/tools/:toolName", async (c) => {
  const toolName = c.req.param("toolName");
  const body = await c.req.json();

  try {
    const result = await neurolink.executeTool(toolName, body);
    return c.json({ result });
  } catch (error) {
    return c.json({
      error: error.message,
    }, 500);
  }
});

// GET /providers - List available providers
router.get("/providers", (c) => {
  return c.json({
    providers: [
      "openai",
      "anthropic",
      "google-ai",
      "vertex",
      "bedrock",
      "azure",
      "mistral",
      "ollama",
      "huggingface",
      "litellm",
      "openrouter",
    ],
  });
});

// GET /models - List available models
router.get("/models", async (c) => {
  const provider = c.req.query("provider");
  return c.json({
    models: [],
    provider,
  });
});

export default router;
`;
  }

  /**
   * Generate OpenAPI spec
   */
  private generateOpenApiSpec(): string {
    const openApiConfig =
      typeof this.config.openapi === "object" ? this.config.openapi : {};

    const spec = {
      openapi: "3.0.3",
      info: {
        title: openApiConfig.title || "NeuroLink API",
        version: openApiConfig.version || "1.0.0",
        description:
          openApiConfig.description || "AI-powered API built with NeuroLink",
      },
      servers: [
        {
          url: "{baseUrl}",
          variables: {
            baseUrl: {
              default: "http://localhost:8080",
              description: "API base URL",
            },
          },
        },
      ],
      paths: {
        "/api/generate": {
          post: {
            summary: "Generate text using AI",
            operationId: "generate",
            requestBody: {
              required: true,
              content: {
                "application/json": {
                  schema: {
                    $ref: "#/components/schemas/GenerateRequest",
                  },
                },
              },
            },
            responses: {
              200: {
                description: "Successful response",
                content: {
                  "application/json": {
                    schema: {
                      $ref: "#/components/schemas/GenerateResponse",
                    },
                  },
                },
              },
            },
          },
        },
        "/api/stream": {
          post: {
            summary: "Stream text generation",
            operationId: "stream",
            requestBody: {
              required: true,
              content: {
                "application/json": {
                  schema: {
                    $ref: "#/components/schemas/GenerateRequest",
                  },
                },
              },
            },
            responses: {
              200: {
                description: "Streaming response",
                content: {
                  "text/event-stream": {
                    schema: {
                      type: "string",
                    },
                  },
                },
              },
            },
          },
        },
        "/api/tools": {
          get: {
            summary: "List available tools",
            operationId: "listTools",
            responses: {
              200: {
                description: "List of tools",
              },
            },
          },
        },
        "/api/providers": {
          get: {
            summary: "List available AI providers",
            operationId: "listProviders",
            responses: {
              200: {
                description: "List of providers",
              },
            },
          },
        },
        "/health": {
          get: {
            summary: "Health check endpoint",
            operationId: "healthCheck",
            responses: {
              200: {
                description: "Service is healthy",
              },
            },
          },
        },
      },
      components: {
        schemas: {
          GenerateRequest: {
            type: "object",
            properties: {
              prompt: {
                type: "string",
                description: "The prompt to generate from",
              },
              model: {
                type: "string",
                description: "Model to use",
              },
              provider: {
                type: "string",
                description: "AI provider",
              },
              temperature: {
                type: "number",
                minimum: 0,
                maximum: 2,
              },
              maxTokens: {
                type: "integer",
                minimum: 1,
              },
              system: {
                type: "string",
                description: "System prompt",
              },
            },
            required: ["prompt"],
          },
          GenerateResponse: {
            type: "object",
            properties: {
              content: {
                type: "string",
              },
              provider: {
                type: "string",
              },
              model: {
                type: "string",
              },
              usage: {
                type: "object",
              },
            },
          },
        },
      },
    };

    return JSON.stringify(spec, null, 2);
  }

  /**
   * Generate playground HTML
   */
  private generatePlayground(): string {
    const basePath = this.config.basePath || "/api";

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>NeuroLink Playground</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: system-ui, -apple-system, sans-serif;
      background: #0a0a0a;
      color: #fafafa;
      min-height: 100vh;
      padding: 2rem;
    }
    .container { max-width: 1200px; margin: 0 auto; }
    h1 { margin-bottom: 2rem; font-size: 2rem; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 2rem; }
    .panel {
      background: #1a1a1a;
      border-radius: 8px;
      padding: 1.5rem;
      border: 1px solid #333;
    }
    h2 { margin-bottom: 1rem; font-size: 1.25rem; color: #888; }
    textarea {
      width: 100%;
      height: 200px;
      background: #0a0a0a;
      border: 1px solid #333;
      border-radius: 4px;
      padding: 1rem;
      color: #fafafa;
      font-family: monospace;
      resize: vertical;
    }
    button {
      margin-top: 1rem;
      padding: 0.75rem 1.5rem;
      background: #3b82f6;
      color: white;
      border: none;
      border-radius: 4px;
      cursor: pointer;
      font-size: 1rem;
    }
    button:hover { background: #2563eb; }
    button:disabled { background: #666; cursor: not-allowed; }
    .response {
      background: #0a0a0a;
      border: 1px solid #333;
      border-radius: 4px;
      padding: 1rem;
      min-height: 200px;
      font-family: monospace;
      white-space: pre-wrap;
      overflow: auto;
    }
    .streaming { color: #22c55e; }
    .error { color: #ef4444; }
    select {
      width: 100%;
      padding: 0.5rem;
      background: #0a0a0a;
      border: 1px solid #333;
      border-radius: 4px;
      color: #fafafa;
      margin-bottom: 1rem;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>NeuroLink Playground</h1>
    <div class="grid">
      <div class="panel">
        <h2>Input</h2>
        <select id="endpoint">
          <option value="${basePath}/generate">Generate</option>
          <option value="${basePath}/stream">Stream</option>
          <option value="${basePath}/tools">List Tools</option>
        </select>
        <textarea id="input" placeholder="Enter your prompt...">Explain quantum computing in simple terms.</textarea>
        <button onclick="sendRequest()">Send Request</button>
      </div>
      <div class="panel">
        <h2>Response</h2>
        <div id="response" class="response">Response will appear here...</div>
      </div>
    </div>
  </div>
  <script>
    async function sendRequest() {
      const endpoint = document.getElementById('endpoint').value;
      const input = document.getElementById('input').value;
      const responseEl = document.getElementById('response');

      responseEl.className = 'response';
      responseEl.textContent = 'Loading...';

      try {
        if (endpoint.includes('/stream')) {
          responseEl.className = 'response streaming';
          responseEl.textContent = '';

          const response = await fetch(endpoint, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ prompt: input }),
          });

          const reader = response.body.getReader();
          const decoder = new TextDecoder();

          while (true) {
            const { done, value } = await reader.read();
            if (done) break;
            responseEl.textContent += decoder.decode(value);
          }
        } else if (endpoint.includes('/tools')) {
          const response = await fetch(endpoint);
          const data = await response.json();
          responseEl.textContent = JSON.stringify(data, null, 2);
        } else {
          const response = await fetch(endpoint, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ prompt: input }),
          });
          const data = await response.json();
          responseEl.textContent = JSON.stringify(data, null, 2);
        }
      } catch (error) {
        responseEl.className = 'response error';
        responseEl.textContent = 'Error: ' + error.message;
      }
    }
  </script>
</body>
</html>`;
  }
}

export default ServerGenerator;
